# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ventPrincipal = QtWidgets.QTextBrowser(self.centralwidget)
        self.ventPrincipal.setGeometry(QtCore.QRect(9, 9, 421, 531))
        self.ventPrincipal.setObjectName("ventPrincipal")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(440, 0, 251, 341))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(20, 10, 231, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.instructions = QtWidgets.QLabel(self.frame)
        self.instructions.setWordWrap(True)
        self.instructions.setObjectName("instructions")
        self.verticalLayout_2.addWidget(self.instructions)
        self.butExec = QtWidgets.QPushButton(self.frame_3)
        self.butExec.setGeometry(QtCore.QRect(30, 230, 101, 81))
        self.butExec.setObjectName("butExec")
        self.butReset = QtWidgets.QPushButton(self.frame_3)
        self.butReset.setGeometry(QtCore.QRect(150, 240, 91, 51))
        self.butReset.setObjectName("butReset")
        self.systmes = QtWidgets.QLabel(self.centralwidget)
        self.systmes.setGeometry(QtCore.QRect(480, 370, 201, 61))
        self.systmes.setObjectName("systmes")
        self.chapterSel = QtWidgets.QComboBox(self.centralwidget)
        self.chapterSel.setGeometry(QtCore.QRect(480, 470, 201, 20))
        self.chapterSel.setEditable(True)
        self.chapterSel.setMaxVisibleItems(10)
        self.chapterSel.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.chapterSel.setObjectName("chapterSel")
        self.author = QtWidgets.QLabel(self.centralwidget)
        self.author.setGeometry(QtCore.QRect(536, 530, 131, 20))
        self.author.setObjectName("author")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuPost_processing = QtWidgets.QMenu(self.menubar)
        self.menuPost_processing.setObjectName("menuPost_processing")
        self.menuCharts = QtWidgets.QMenu(self.menuPost_processing)
        self.menuCharts.setObjectName("menuCharts")
        self.menuTables = QtWidgets.QMenu(self.menuPost_processing)
        self.menuTables.setObjectName("menuTables")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuTrees = QtWidgets.QMenu(self.menuTools)
        self.menuTrees.setObjectName("menuTrees")
        self.menuAdvanced = QtWidgets.QMenu(self.menubar)
        self.menuAdvanced.setObjectName("menuAdvanced")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_CVS = QtWidgets.QAction(MainWindow)
        self.actionSave_CVS.setObjectName("actionSave_CVS")
        self.actionTokenization = QtWidgets.QAction(MainWindow)
        self.actionTokenization.setObjectName("actionTokenization")
        self.actionCompare = QtWidgets.QAction(MainWindow)
        self.actionCompare.setObjectName("actionCompare")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionProfile = QtWidgets.QAction(MainWindow)
        self.actionProfile.setObjectName("actionProfile")
        self.actionCluster = QtWidgets.QAction(MainWindow)
        self.actionCluster.setObjectName("actionCluster")
        self.actionCount = QtWidgets.QAction(MainWindow)
        self.actionCount.setObjectName("actionCount")
        self.actionPhrase_count = QtWidgets.QAction(MainWindow)
        self.actionPhrase_count.setObjectName("actionPhrase_count")
        self.actionFrecuency = QtWidgets.QAction(MainWindow)
        self.actionFrecuency.setObjectName("actionFrecuency")
        self.actionRaw_doc_tree = QtWidgets.QAction(MainWindow)
        self.actionRaw_doc_tree.setObjectName("actionRaw_doc_tree")
        self.actionChapters_tree = QtWidgets.QAction(MainWindow)
        self.actionChapters_tree.setObjectName("actionChapters_tree")
        self.actionWord_Tree = QtWidgets.QAction(MainWindow)
        self.actionWord_Tree.setObjectName("actionWord_Tree")
        self.actionStatistic_analysis = QtWidgets.QAction(MainWindow)
        self.actionStatistic_analysis.setObjectName("actionStatistic_analysis")
        self.actionSentiment_analysis = QtWidgets.QAction(MainWindow)
        self.actionSentiment_analysis.setObjectName("actionSentiment_analysis")
        self.actionSimilarity = QtWidgets.QAction(MainWindow)
        self.actionSimilarity.setObjectName("actionSimilarity")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionSave_CVS)
        self.menuCharts.addAction(self.actionHistogram)
        self.menuCharts.addAction(self.actionProfile)
        self.menuCharts.addAction(self.actionCluster)
        self.menuCharts.addAction(self.actionFrecuency)
        self.menuTables.addAction(self.actionCount)
        self.menuTables.addAction(self.actionPhrase_count)
        self.menuPost_processing.addAction(self.menuCharts.menuAction())
        self.menuPost_processing.addAction(self.menuTables.menuAction())
        self.menuPost_processing.addAction(self.actionCompare)
        self.menuTrees.addAction(self.actionRaw_doc_tree)
        self.menuTrees.addAction(self.actionChapters_tree)
        self.menuTrees.addAction(self.actionWord_Tree)
        self.menuTools.addAction(self.menuTrees.menuAction())
        self.menuTools.addAction(self.actionStatistic_analysis)
        self.menuAdvanced.addAction(self.actionSentiment_analysis)
        self.menuAdvanced.addAction(self.actionSimilarity)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPost_processing.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAdvanced.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text analysis- V.0.1 \"Thamsanqa\""))
        self.instructions.setText(_translate("MainWindow", "<html><head/><body><p>Sequence:</p><p>1- Load <span style=\" font-weight:600;\">.txt</span> file</p><p>2- <span style=\" font-weight:600;\">Execute </span>for general text decomposition</p><p>3- Select<span style=\" font-weight:600;\"> Chapte</span>r (single or all)</p><p>4- Perform <span style=\" font-weight:600;\">postprocessing</span> analysis</p></body></html>"))
        self.butExec.setText(_translate("MainWindow", "Execute"))
        self.butReset.setText(_translate("MainWindow", "Reset"))
        self.systmes.setText(_translate("MainWindow", "System messages"))
        self.chapterSel.setCurrentText(_translate("MainWindow", "Chapter select"))
        self.author.setText(_translate("MainWindow", "Jaime Andrés Vélez -2018"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuPost_processing.setTitle(_translate("MainWindow", "Post processing"))
        self.menuCharts.setTitle(_translate("MainWindow", "Charts"))
        self.menuTables.setTitle(_translate("MainWindow", "Tables"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuTrees.setTitle(_translate("MainWindow", "Trees"))
        self.menuAdvanced.setTitle(_translate("MainWindow", "Advanced"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave_CVS.setText(_translate("MainWindow", "Save CVS"))
        self.actionTokenization.setText(_translate("MainWindow", "Tokenization"))
        self.actionCompare.setText(_translate("MainWindow", "Compare"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionProfile.setText(_translate("MainWindow", "Profile"))
        self.actionCluster.setText(_translate("MainWindow", "Cluster"))
        self.actionCount.setText(_translate("MainWindow", "Count"))
        self.actionPhrase_count.setText(_translate("MainWindow", "Phrase count"))
        self.actionFrecuency.setText(_translate("MainWindow", "Frecuency"))
        self.actionRaw_doc_tree.setText(_translate("MainWindow", "Raw doc tree"))
        self.actionChapters_tree.setText(_translate("MainWindow", "Chapters tree"))
        self.actionWord_Tree.setText(_translate("MainWindow", "Word Tree"))
        self.actionStatistic_analysis.setText(_translate("MainWindow", "Statistic analysis"))
        self.actionSentiment_analysis.setText(_translate("MainWindow", "Sentiment analysis"))
        self.actionSimilarity.setText(_translate("MainWindow", "Similarity"))

