# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ventPrincipal = QtWidgets.QTextBrowser(self.centralwidget)
        self.ventPrincipal.setGeometry(QtCore.QRect(9, 9, 421, 531))
        self.ventPrincipal.setObjectName("ventPrincipal")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(440, 0, 251, 211))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(20, 10, 90, 83))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chWords = QtWidgets.QCheckBox(self.frame)
        self.chWords.setObjectName("chWords")
        self.verticalLayout_2.addWidget(self.chWords)
        self.chParagraph = QtWidgets.QCheckBox(self.frame)
        self.chParagraph.setObjectName("chParagraph")
        self.verticalLayout_2.addWidget(self.chParagraph)
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(160, 10, 90, 83))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chPhrases = QtWidgets.QCheckBox(self.frame_2)
        self.chPhrases.setObjectName("chPhrases")
        self.verticalLayout_3.addWidget(self.chPhrases)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_3.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_3.addWidget(self.checkBox_6)
        self.butExec = QtWidgets.QPushButton(self.frame_3)
        self.butExec.setGeometry(QtCore.QRect(30, 112, 101, 81))
        self.butExec.setObjectName("butExec")
        self.butReset = QtWidgets.QPushButton(self.frame_3)
        self.butReset.setGeometry(QtCore.QRect(160, 170, 75, 23))
        self.butReset.setObjectName("butReset")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuProcessing = QtWidgets.QMenu(self.menubar)
        self.menuProcessing.setObjectName("menuProcessing")
        self.menuPost_processing = QtWidgets.QMenu(self.menubar)
        self.menuPost_processing.setObjectName("menuPost_processing")
        self.menuCharts = QtWidgets.QMenu(self.menuPost_processing)
        self.menuCharts.setObjectName("menuCharts")
        self.menuTables = QtWidgets.QMenu(self.menuPost_processing)
        self.menuTables.setObjectName("menuTables")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_CVS = QtWidgets.QAction(MainWindow)
        self.actionSave_CVS.setObjectName("actionSave_CVS")
        self.actionTokenization = QtWidgets.QAction(MainWindow)
        self.actionTokenization.setObjectName("actionTokenization")
        self.actionCompare = QtWidgets.QAction(MainWindow)
        self.actionCompare.setObjectName("actionCompare")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionProfile = QtWidgets.QAction(MainWindow)
        self.actionProfile.setObjectName("actionProfile")
        self.actionCluster = QtWidgets.QAction(MainWindow)
        self.actionCluster.setObjectName("actionCluster")
        self.actionCount = QtWidgets.QAction(MainWindow)
        self.actionCount.setObjectName("actionCount")
        self.actionPhrase_count = QtWidgets.QAction(MainWindow)
        self.actionPhrase_count.setObjectName("actionPhrase_count")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionSave_CVS)
        self.menuProcessing.addAction(self.actionTokenization)
        self.menuCharts.addAction(self.actionHistogram)
        self.menuCharts.addAction(self.actionProfile)
        self.menuCharts.addAction(self.actionCluster)
        self.menuTables.addAction(self.actionCount)
        self.menuTables.addAction(self.actionPhrase_count)
        self.menuPost_processing.addAction(self.menuCharts.menuAction())
        self.menuPost_processing.addAction(self.menuTables.menuAction())
        self.menuPost_processing.addAction(self.actionCompare)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuProcessing.menuAction())
        self.menubar.addAction(self.menuPost_processing.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text analysis"))
        self.chWords.setText(_translate("MainWindow", "Words"))
        self.chParagraph.setText(_translate("MainWindow", "Pharagraph"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.chPhrases.setText(_translate("MainWindow", "Phrases"))
        self.checkBox_5.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_6.setText(_translate("MainWindow", "CheckBox"))
        self.butExec.setText(_translate("MainWindow", "Execute"))
        self.butReset.setText(_translate("MainWindow", "Reset"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuProcessing.setTitle(_translate("MainWindow", "Processing"))
        self.menuPost_processing.setTitle(_translate("MainWindow", "Post processing"))
        self.menuCharts.setTitle(_translate("MainWindow", "Charts"))
        self.menuTables.setTitle(_translate("MainWindow", "Tables"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave_CVS.setText(_translate("MainWindow", "Save CVS"))
        self.actionTokenization.setText(_translate("MainWindow", "Tokenization"))
        self.actionCompare.setText(_translate("MainWindow", "Compare"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionProfile.setText(_translate("MainWindow", "Profile"))
        self.actionCluster.setText(_translate("MainWindow", "Cluster"))
        self.actionCount.setText(_translate("MainWindow", "Count"))
        self.actionPhrase_count.setText(_translate("MainWindow", "Phrase count"))




if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
